
// This file has been generated by the GUI designer. Do not modify.
namespace bazar
{
	public partial class ContractsReportDlg
	{
		private global::Gtk.Table table1;

		private global::Gtk.ComboBox comboOrg;

		private global::Gtk.HBox hbox1;

		private global::Gtk.RadioButton radiobuttonAll;

		private global::Gtk.RadioButton radiobuttonActive;

		private global::Gtk.Label label1;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget bazar.ContractsReportDlg
			this.Name = "bazar.ContractsReportDlg";
			this.Title = global::Mono.Unix.Catalog.GetString("Реестр договоров");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child bazar.ContractsReportDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.comboOrg = global::Gtk.ComboBox.NewText();
			this.comboOrg.Name = "comboOrg";
			this.table1.Add(this.comboOrg);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.comboOrg]));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radiobuttonAll = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Все договора"));
			this.radiobuttonAll.CanFocus = true;
			this.radiobuttonAll.Name = "radiobuttonAll";
			this.radiobuttonAll.DrawIndicator = true;
			this.radiobuttonAll.UseUnderline = true;
			this.radiobuttonAll.Group = new global::GLib.SList(global::System.IntPtr.Zero);
			this.hbox1.Add(this.radiobuttonAll);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonAll]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.radiobuttonActive = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Только действующие"));
			this.radiobuttonActive.CanFocus = true;
			this.radiobuttonActive.Name = "radiobuttonActive";
			this.radiobuttonActive.DrawIndicator = true;
			this.radiobuttonActive.UseUnderline = true;
			this.radiobuttonActive.Group = this.radiobuttonAll.Group;
			this.hbox1.Add(this.radiobuttonActive);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.radiobuttonActive]));
			w4.Position = 1;
			this.table1.Add(this.hbox1);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.hbox1]));
			w5.TopAttach = ((uint)(1));
			w5.BottomAttach = ((uint)(2));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(0));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Отчет по организации:");
			this.table1.Add(this.label1);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			w1.Add(this.table1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(w1[this.table1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Internal child bazar.ContractsReportDlg.ActionArea
			global::Gtk.HButtonBox w8 = this.ActionArea;
			w8.Name = "dialog1_ActionArea";
			w8.Spacing = 10;
			w8.BorderWidth = ((uint)(5));
			w8.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8[this.buttonCancel]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w10 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w8[this.buttonOk]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 302;
			this.DefaultHeight = 113;
			this.Show();
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
