
// This file has been generated by the GUI designer. Do not modify.
namespace bazar.ReportDialogs
{
	public partial class MetersStatisticsDlg
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label label3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeviewProviders;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label5;

		private global::Gtk.ComboBox comboPeriod;

		private global::Gtk.ComboBox comboYear;

		private global::Gtk.CheckButton checkbuttonOnlyAccruals;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget bazar.ReportDialogs.MetersStatisticsDlg
			this.Name = "bazar.ReportDialogs.MetersStatisticsDlg";
			this.Title = global::Mono.Unix.Catalog.GetString("dialog1");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child bazar.ReportDialogs.MetersStatisticsDlg.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Поставщики");
			this.vbox3.Add(this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeviewProviders = new global::Gtk.TreeView();
			this.treeviewProviders.CanFocus = true;
			this.treeviewProviders.Name = "treeviewProviders";
			this.GtkScrolledWindow.Add(this.treeviewProviders);
			this.vbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow]));
			w4.Position = 1;
			this.vbox2.Add(this.vbox3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox3]));
			w5.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Период:");
			this.hbox1.Add(this.label5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label5]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.comboPeriod = global::Gtk.ComboBox.NewText();
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Январь"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Февраль"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Март"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Апрель"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Май"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Июнь"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Июль"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Август"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Сентябрь"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Октябрь"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Ноябрь"));
			this.comboPeriod.AppendText(global::Mono.Unix.Catalog.GetString("Декабрь"));
			this.comboPeriod.Name = "comboPeriod";
			this.hbox1.Add(this.comboPeriod);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.comboPeriod]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.comboYear = global::Gtk.ComboBox.NewText();
			this.comboYear.Name = "comboYear";
			this.hbox1.Add(this.comboYear);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.comboYear]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.checkbuttonOnlyAccruals = new global::Gtk.CheckButton();
			this.checkbuttonOnlyAccruals.CanFocus = true;
			this.checkbuttonOnlyAccruals.Name = "checkbuttonOnlyAccruals";
			this.checkbuttonOnlyAccruals.Label = global::Mono.Unix.Catalog.GetString("Только с начислениями");
			this.checkbuttonOnlyAccruals.DrawIndicator = true;
			this.checkbuttonOnlyAccruals.UseUnderline = true;
			this.vbox2.Add(this.checkbuttonOnlyAccruals);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.checkbuttonOnlyAccruals]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			w1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w11.Position = 0;
			// Internal child bazar.ReportDialogs.MetersStatisticsDlg.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12[this.buttonCancel]));
			w13.Expand = false;
			w13.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12[this.buttonOk]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 529;
			this.DefaultHeight = 465;
			this.Show();
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
