
// This file has been generated by the GUI designer. Do not modify.
namespace bazar
{
	public partial class IncomeSlip
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Table table1;

		private global::Gtk.ComboBox comboAccrual;

		private global::Gtk.ComboBox comboCash;

		private global::Gtk.ComboBox comboContract;

		private global::Gtk.ComboBox comboOperation;

		private global::Gtk.ComboBox comboOrg;

		private global::Gtk.HBox hboxAccountable;

		private global::Gtk.Entry entryAccountable;

		private global::Gtk.Button buttonAccountableEdit;

		private global::Gtk.HBox hboxLessee;

		private global::Gtk.Entry entryLessee;

		private global::Gtk.Button buttonLesseeEdit;

		private global::Gtk.Label label11;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label labelAccountable;

		private global::Gtk.Label labelAccrual;

		private global::Gtk.Label labelContract;

		private global::Gtk.Label labelLessee;

		private global::Gtk.Table table2;

		private global::QSWidgetLib.DatePicker dateSlip;

		private global::Gtk.Entry entryNumber;

		private global::Gtk.Entry entryUser;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Entry entryIncome;

		private global::Gtk.Button buttonIncome;

		private global::Gtk.Label label2;

		private global::Gtk.Label label6;

		private global::Gtk.Label label7;

		private global::Gtk.Label label9;

		private global::Gtk.Label labelIncomeItem;

		private global::Gtk.SpinButton spinSum;

		private global::bazar.SeparationPayment separationpayment;

		private global::Gtk.Label label5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView textviewDetails;

		private global::QSWidgetLib.MenuButton buttonPrintPayment;

		private global::Gtk.Button buttonPrint;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget bazar.IncomeSlip
			this.Name = "bazar.IncomeSlip";
			this.Title = global::Mono.Unix.Catalog.GetString("Новый приходный ордер");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child bazar.IncomeSlip.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table(((uint)(7)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.comboAccrual = new global::Gtk.ComboBox();
			this.comboAccrual.Name = "comboAccrual";
			this.table1.Add(this.comboAccrual);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.comboAccrual]));
			w2.TopAttach = ((uint)(5));
			w2.BottomAttach = ((uint)(6));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboCash = new global::Gtk.ComboBox();
			this.comboCash.Name = "comboCash";
			this.table1.Add(this.comboCash);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.comboCash]));
			w3.TopAttach = ((uint)(2));
			w3.BottomAttach = ((uint)(3));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboContract = new global::Gtk.ComboBox();
			this.comboContract.Name = "comboContract";
			this.table1.Add(this.comboContract);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.comboContract]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboOperation = global::Gtk.ComboBox.NewText();
			this.comboOperation.AppendText(global::Mono.Unix.Catalog.GetString("Прочий приход"));
			this.comboOperation.AppendText(global::Mono.Unix.Catalog.GetString("Возврат от подотчетного лица"));
			this.comboOperation.AppendText(global::Mono.Unix.Catalog.GetString("Оплата по начислению"));
			this.comboOperation.Name = "comboOperation";
			this.comboOperation.Active = 0;
			this.table1.Add(this.comboOperation);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.comboOperation]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.XOptions = ((global::Gtk.AttachOptions)(4));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboOrg = new global::Gtk.ComboBox();
			this.comboOrg.Name = "comboOrg";
			this.table1.Add(this.comboOrg);
			global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.comboOrg]));
			w6.TopAttach = ((uint)(1));
			w6.BottomAttach = ((uint)(2));
			w6.LeftAttach = ((uint)(1));
			w6.RightAttach = ((uint)(2));
			w6.XOptions = ((global::Gtk.AttachOptions)(4));
			w6.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hboxAccountable = new global::Gtk.HBox();
			this.hboxAccountable.Name = "hboxAccountable";
			this.hboxAccountable.Spacing = 6;
			// Container child hboxAccountable.Gtk.Box+BoxChild
			this.entryAccountable = new global::Gtk.Entry();
			this.entryAccountable.CanFocus = true;
			this.entryAccountable.Name = "entryAccountable";
			this.entryAccountable.IsEditable = false;
			this.entryAccountable.InvisibleChar = '●';
			this.hboxAccountable.Add(this.entryAccountable);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hboxAccountable[this.entryAccountable]));
			w7.Position = 0;
			// Container child hboxAccountable.Gtk.Box+BoxChild
			this.buttonAccountableEdit = new global::Gtk.Button();
			this.buttonAccountableEdit.CanFocus = true;
			this.buttonAccountableEdit.Name = "buttonAccountableEdit";
			this.buttonAccountableEdit.UseUnderline = true;
			global::Gtk.Image w8 = new global::Gtk.Image();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonAccountableEdit.Image = w8;
			this.hboxAccountable.Add(this.buttonAccountableEdit);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hboxAccountable[this.buttonAccountableEdit]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.table1.Add(this.hboxAccountable);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.hboxAccountable]));
			w10.TopAttach = ((uint)(6));
			w10.BottomAttach = ((uint)(7));
			w10.LeftAttach = ((uint)(1));
			w10.RightAttach = ((uint)(2));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hboxLessee = new global::Gtk.HBox();
			this.hboxLessee.Name = "hboxLessee";
			this.hboxLessee.Spacing = 6;
			// Container child hboxLessee.Gtk.Box+BoxChild
			this.entryLessee = new global::Gtk.Entry();
			this.entryLessee.CanFocus = true;
			this.entryLessee.Name = "entryLessee";
			this.entryLessee.IsEditable = false;
			this.entryLessee.InvisibleChar = '●';
			this.hboxLessee.Add(this.entryLessee);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxLessee[this.entryLessee]));
			w11.Position = 0;
			// Container child hboxLessee.Gtk.Box+BoxChild
			this.buttonLesseeEdit = new global::Gtk.Button();
			this.buttonLesseeEdit.TooltipMarkup = "Выбрать контрагента";
			this.buttonLesseeEdit.CanFocus = true;
			this.buttonLesseeEdit.Name = "buttonLesseeEdit";
			this.buttonLesseeEdit.UseUnderline = true;
			global::Gtk.Image w12 = new global::Gtk.Image();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonLesseeEdit.Image = w12;
			this.hboxLessee.Add(this.buttonLesseeEdit);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hboxLessee[this.buttonLesseeEdit]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.table1.Add(this.hboxLessee);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.hboxLessee]));
			w14.TopAttach = ((uint)(3));
			w14.BottomAttach = ((uint)(4));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Вид операции:</b>");
			this.label11.UseMarkup = true;
			this.table1.Add(this.label11);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.label11]));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Организация<span foreground=\"red\">*</span>:");
			this.label3.UseMarkup = true;
			this.table1.Add(this.label3);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.label3]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Касса<span foreground=\"red\">*</span>:");
			this.label4.UseMarkup = true;
			this.table1.Add(this.label4);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.label4]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelAccountable = new global::Gtk.Label();
			this.labelAccountable.Name = "labelAccountable";
			this.labelAccountable.LabelProp = global::Mono.Unix.Catalog.GetString("Подотчетное лицо<span foreground=\"red\">*</span>:");
			this.labelAccountable.UseMarkup = true;
			this.table1.Add(this.labelAccountable);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.labelAccountable]));
			w18.TopAttach = ((uint)(6));
			w18.BottomAttach = ((uint)(7));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelAccrual = new global::Gtk.Label();
			this.labelAccrual.Name = "labelAccrual";
			this.labelAccrual.Xalign = 1F;
			this.labelAccrual.LabelProp = global::Mono.Unix.Catalog.GetString("По начислению<span foreground=\"red\">*</span>:");
			this.labelAccrual.UseMarkup = true;
			this.table1.Add(this.labelAccrual);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.labelAccrual]));
			w19.TopAttach = ((uint)(5));
			w19.BottomAttach = ((uint)(6));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelContract = new global::Gtk.Label();
			this.labelContract.Name = "labelContract";
			this.labelContract.Xalign = 1F;
			this.labelContract.LabelProp = global::Mono.Unix.Catalog.GetString("Договор:");
			this.table1.Add(this.labelContract);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.labelContract]));
			w20.TopAttach = ((uint)(4));
			w20.BottomAttach = ((uint)(5));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelLessee = new global::Gtk.Label();
			this.labelLessee.Name = "labelLessee";
			this.labelLessee.Xalign = 1F;
			this.labelLessee.LabelProp = global::Mono.Unix.Catalog.GetString("Арендатор<span foreground=\"red\">*</span>:");
			this.labelLessee.UseMarkup = true;
			this.table1.Add(this.labelLessee);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1[this.labelLessee]));
			w21.TopAttach = ((uint)(3));
			w21.BottomAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add(this.table1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.table1]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table(((uint)(5)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			this.table2.BorderWidth = ((uint)(3));
			// Container child table2.Gtk.Table+TableChild
			this.dateSlip = new global::QSWidgetLib.DatePicker();
			this.dateSlip.Sensitive = false;
			this.dateSlip.Events = ((global::Gdk.EventMask)(256));
			this.dateSlip.Name = "dateSlip";
			this.dateSlip.WithTime = false;
			this.dateSlip.Date = new global::System.DateTime(0);
			this.dateSlip.IsEditable = true;
			this.dateSlip.AutoSeparation = true;
			this.table2.Add(this.dateSlip);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2[this.dateSlip]));
			w23.TopAttach = ((uint)(1));
			w23.BottomAttach = ((uint)(2));
			w23.LeftAttach = ((uint)(1));
			w23.RightAttach = ((uint)(2));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryNumber = new global::Gtk.Entry();
			this.entryNumber.Sensitive = false;
			this.entryNumber.CanFocus = true;
			this.entryNumber.Name = "entryNumber";
			this.entryNumber.Text = global::Mono.Unix.Catalog.GetString("Не назначен");
			this.entryNumber.IsEditable = false;
			this.entryNumber.InvisibleChar = '●';
			this.table2.Add(this.entryNumber);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2[this.entryNumber]));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.XOptions = ((global::Gtk.AttachOptions)(4));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryUser = new global::Gtk.Entry();
			this.entryUser.Sensitive = false;
			this.entryUser.CanFocus = true;
			this.entryUser.Name = "entryUser";
			this.entryUser.IsEditable = true;
			this.entryUser.InvisibleChar = '●';
			this.table2.Add(this.entryUser);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2[this.entryUser]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryIncome = new global::Gtk.Entry();
			this.entryIncome.CanFocus = true;
			this.entryIncome.Name = "entryIncome";
			this.entryIncome.IsEditable = false;
			this.entryIncome.InvisibleChar = '●';
			this.hbox4.Add(this.entryIncome);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.entryIncome]));
			w26.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonIncome = new global::Gtk.Button();
			this.buttonIncome.CanFocus = true;
			this.buttonIncome.Name = "buttonIncome";
			this.buttonIncome.UseUnderline = true;
			global::Gtk.Image w27 = new global::Gtk.Image();
			w27.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonIncome.Image = w27;
			this.hbox4.Add(this.buttonIncome);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonIncome]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			this.table2.Add(this.hbox4);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table2[this.hbox4]));
			w29.TopAttach = ((uint)(3));
			w29.BottomAttach = ((uint)(4));
			w29.LeftAttach = ((uint)(1));
			w29.RightAttach = ((uint)(2));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Номер ордера:");
			this.table2.Add(this.label2);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table2[this.label2]));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Дата документа:");
			this.table2.Add(this.label6);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table2[this.label6]));
			w31.TopAttach = ((uint)(1));
			w31.BottomAttach = ((uint)(2));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Пользователь:");
			this.table2.Add(this.label7);
			global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table2[this.label7]));
			w32.TopAttach = ((uint)(2));
			w32.BottomAttach = ((uint)(3));
			w32.XOptions = ((global::Gtk.AttachOptions)(4));
			w32.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Сумма<span foreground=\"red\">*</span>:");
			this.label9.UseMarkup = true;
			this.table2.Add(this.label9);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table2[this.label9]));
			w33.TopAttach = ((uint)(4));
			w33.BottomAttach = ((uint)(5));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelIncomeItem = new global::Gtk.Label();
			this.labelIncomeItem.Name = "labelIncomeItem";
			this.labelIncomeItem.Xalign = 1F;
			this.labelIncomeItem.LabelProp = global::Mono.Unix.Catalog.GetString("Статья дохода<span foreground=\"red\">*</span>:");
			this.labelIncomeItem.UseMarkup = true;
			this.table2.Add(this.labelIncomeItem);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2[this.labelIncomeItem]));
			w34.TopAttach = ((uint)(3));
			w34.BottomAttach = ((uint)(4));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.spinSum = new global::Gtk.SpinButton(0D, 100000000D, 100D);
			this.spinSum.CanFocus = true;
			this.spinSum.Name = "spinSum";
			this.spinSum.Adjustment.PageIncrement = 1000D;
			this.spinSum.ClimbRate = 1D;
			this.spinSum.Digits = ((uint)(2));
			this.spinSum.Numeric = true;
			this.table2.Add(this.spinSum);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table2[this.spinSum]));
			w35.TopAttach = ((uint)(4));
			w35.BottomAttach = ((uint)(5));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add(this.table2);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.table2]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox2.Add(this.hbox1);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.separationpayment = new global::bazar.SeparationPayment();
			this.separationpayment.Events = ((global::Gdk.EventMask)(256));
			this.separationpayment.Name = "separationpayment";
			this.separationpayment.PaymentSum = 0m;
			this.separationpayment.PaymentId = 0;
			this.separationpayment.AccrualId = 0;
			this.vbox2.Add(this.separationpayment);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.separationpayment]));
			w38.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Основание:");
			this.vbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label5]));
			w39.Position = 2;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow1.BorderWidth = ((uint)(3));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.textviewDetails = new global::Gtk.TextView();
			this.textviewDetails.CanFocus = true;
			this.textviewDetails.Name = "textviewDetails";
			this.textviewDetails.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow1.Add(this.textviewDetails);
			this.vbox2.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow1]));
			w41.Position = 3;
			w1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w42.Position = 0;
			// Internal child bazar.IncomeSlip.ActionArea
			global::Gtk.HButtonBox w43 = this.ActionArea;
			w43.Name = "dialog1_ActionArea";
			w43.Spacing = 10;
			w43.BorderWidth = ((uint)(5));
			w43.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPrintPayment = new global::QSWidgetLib.MenuButton();
			this.buttonPrintPayment.CanFocus = true;
			this.buttonPrintPayment.Name = "buttonPrintPayment";
			this.buttonPrintPayment.UseUnderline = true;
			this.buttonPrintPayment.UseMarkup = false;
			this.buttonPrintPayment.LabelXAlign = 0F;
			this.buttonPrintPayment.Label = global::Mono.Unix.Catalog.GetString("Квитанция");
			global::Gtk.Image w44 = new global::Gtk.Image();
			w44.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-print", global::Gtk.IconSize.Button);
			this.buttonPrintPayment.Image = w44;
			this.AddActionWidget(this.buttonPrintPayment, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w45 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w43[this.buttonPrintPayment]));
			w45.Expand = false;
			w45.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPrint = new global::Gtk.Button();
			this.buttonPrint.Sensitive = false;
			this.buttonPrint.CanFocus = true;
			this.buttonPrint.Name = "buttonPrint";
			this.buttonPrint.UseUnderline = true;
			this.buttonPrint.Label = global::Mono.Unix.Catalog.GetString("Печать");
			global::Gtk.Image w46 = new global::Gtk.Image();
			w46.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-print", global::Gtk.IconSize.Button);
			this.buttonPrint.Image = w46;
			this.AddActionWidget(this.buttonPrint, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w47 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w43[this.buttonPrint]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString("О_тменить");
			global::Gtk.Image w48 = new global::Gtk.Image();
			w48.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w48;
			this.AddActionWidget(this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w49 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w43[this.buttonCancel]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString("_OK");
			global::Gtk.Image w50 = new global::Gtk.Image();
			w50.Pixbuf = global::Stetic.IconLoader.LoadIcon(this, "gtk-ok", global::Gtk.IconSize.Menu);
			this.buttonOk.Image = w50;
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w51 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w43[this.buttonOk]));
			w51.Position = 3;
			w51.Expand = false;
			w51.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 729;
			this.DefaultHeight = 625;
			this.Show();
			this.buttonLesseeEdit.Clicked += new global::System.EventHandler(this.OnButtonLesseeEditClicked);
			this.buttonAccountableEdit.Clicked += new global::System.EventHandler(this.OnButtonAccountableEditClicked);
			this.comboOrg.Changed += new global::System.EventHandler(this.OnComboOrgChanged);
			this.comboOperation.Changed += new global::System.EventHandler(this.OnComboOperationChanged);
			this.comboContract.Changed += new global::System.EventHandler(this.OnComboContractChanged);
			this.comboCash.Changed += new global::System.EventHandler(this.OnComboCashChanged);
			this.comboAccrual.Changed += new global::System.EventHandler(this.OnComboAccrualChanged);
			this.spinSum.ValueChanged += new global::System.EventHandler(this.OnSpinSumValueChanged);
			this.buttonIncome.Clicked += new global::System.EventHandler(this.OnButtonIncomeClicked);
			this.separationpayment.CanSaveStateChanged += new global::System.EventHandler(this.OnSeparationpaymentCanSaveStateChanged);
			this.buttonPrintPayment.Clicked += new global::System.EventHandler(this.OnButtonPrintPaymentClicked);
			this.buttonPrint.Clicked += new global::System.EventHandler(this.OnButtonPrintClicked);
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
