
// This file has been generated by the GUI designer. Do not modify.
namespace bazar
{
	public partial class Contract
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Table table2;
		private global::Gtk.ComboBox comboOrg;
		private global::Gtk.ComboBox comboPayDay;
		private global::QSWidgetLib.DatePicker datepickerSign;
		private global::Gtk.Entry entryNumber;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Entry entryLessee;
		private global::Gtk.Button buttonLesseeOpen;
		private global::Gtk.Button buttonLesseeEdit;
		private global::Gtk.HBox hbox5;
		private global::Gtk.ComboBox comboPlaceT;
		private global::Gtk.Label label1;
		private global::Gtk.ComboBox comboPlaceNo;
		private global::Gtk.Label labelArea;
		private global::Gtk.Label label10;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;
		private global::Gtk.Label label8;
		private global::Gtk.Label label9;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Table table3;
		private global::QSWidgetLib.DatePicker datepickerCancel;
		private global::QSWidgetLib.DatePicker datepickerEnd;
		private global::QSWidgetLib.DatePicker datepickerStart;
		private global::Gtk.Label label11;
		private global::Gtk.Label label12;
		private global::Gtk.Label label13;
		private global::Gtk.Frame frame1;
		private global::Gtk.Alignment GtkAlignment8;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textComments;
		private global::Gtk.Label GtkLabel8;
		private global::Gtk.Label label14;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView treeviewServices;
		private global::Gtk.HBox hbox7;
		private global::Gtk.VBox vbox4;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Button buttonAddService;
		private global::Gtk.Button buttonDelService;
		private global::Gtk.Label labelSum;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget bazar.Contract
			this.Name = "bazar.Contract";
			this.Title = global::Mono.Unix.Catalog.GetString ("Новый договор");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child bazar.Contract.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(6)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			// Container child table2.Gtk.Table+TableChild
			this.comboOrg = new global::Gtk.ComboBox ();
			this.comboOrg.Name = "comboOrg";
			this.table2.Add (this.comboOrg);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table2 [this.comboOrg]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.comboPayDay = global::Gtk.ComboBox.NewText ();
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("Не установлен"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("1"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("2"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("3"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("4"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("5"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("6"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("7"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("8"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("9"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("10"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("11"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("12"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("13"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("14"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("15"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("16"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("17"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("18"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("19"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("20"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("21"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("22"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("23"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("24"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("25"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("26"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("27"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("28"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("29"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("30"));
			this.comboPayDay.AppendText (global::Mono.Unix.Catalog.GetString ("31"));
			this.comboPayDay.Name = "comboPayDay";
			this.comboPayDay.Active = 0;
			this.table2.Add (this.comboPayDay);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table2 [this.comboPayDay]));
			w3.TopAttach = ((uint)(5));
			w3.BottomAttach = ((uint)(6));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.datepickerSign = new global::QSWidgetLib.DatePicker ();
			this.datepickerSign.Events = ((global::Gdk.EventMask)(256));
			this.datepickerSign.Name = "datepickerSign";
			this.datepickerSign.Date = new global::System.DateTime (0);
			this.datepickerSign.IsEditable = true;
			this.datepickerSign.AutoSeparation = true;
			this.table2.Add (this.datepickerSign);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table2 [this.datepickerSign]));
			w4.TopAttach = ((uint)(4));
			w4.BottomAttach = ((uint)(5));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryNumber = new global::Gtk.Entry ();
			this.entryNumber.CanFocus = true;
			this.entryNumber.Name = "entryNumber";
			this.entryNumber.IsEditable = true;
			this.entryNumber.MaxLength = 15;
			this.entryNumber.InvisibleChar = '•';
			this.table2.Add (this.entryNumber);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryNumber]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryLessee = new global::Gtk.Entry ();
			this.entryLessee.CanFocus = true;
			this.entryLessee.Name = "entryLessee";
			this.entryLessee.IsEditable = false;
			this.entryLessee.InvisibleChar = '•';
			this.hbox1.Add (this.entryLessee);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.entryLessee]));
			w6.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonLesseeOpen = new global::Gtk.Button ();
			this.buttonLesseeOpen.TooltipMarkup = "Открыть текущего арендатора";
			this.buttonLesseeOpen.Sensitive = false;
			this.buttonLesseeOpen.CanFocus = true;
			this.buttonLesseeOpen.Name = "buttonLesseeOpen";
			this.buttonLesseeOpen.UseUnderline = true;
			global::Gtk.Image w7 = new global::Gtk.Image ();
			w7.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-open", global::Gtk.IconSize.Menu);
			this.buttonLesseeOpen.Image = w7;
			this.hbox1.Add (this.buttonLesseeOpen);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonLesseeOpen]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.buttonLesseeEdit = new global::Gtk.Button ();
			this.buttonLesseeEdit.TooltipMarkup = "Изменить арендатора";
			this.buttonLesseeEdit.CanFocus = true;
			this.buttonLesseeEdit.Name = "buttonLesseeEdit";
			this.buttonLesseeEdit.UseUnderline = true;
			global::Gtk.Image w9 = new global::Gtk.Image ();
			w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			this.buttonLesseeEdit.Image = w9;
			this.hbox1.Add (this.buttonLesseeEdit);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.buttonLesseeEdit]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.table2.Add (this.hbox1);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox1]));
			w11.TopAttach = ((uint)(3));
			w11.BottomAttach = ((uint)(4));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboPlaceT = new global::Gtk.ComboBox ();
			this.comboPlaceT.Name = "comboPlaceT";
			this.hbox5.Add (this.comboPlaceT);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.comboPlaceT]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("-");
			this.hbox5.Add (this.label1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label1]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboPlaceNo = global::Gtk.ComboBox.NewText ();
			this.comboPlaceNo.Name = "comboPlaceNo";
			this.hbox5.Add (this.comboPlaceNo);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.comboPlaceNo]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.labelArea = new global::Gtk.Label ();
			this.labelArea.TooltipMarkup = "Площадь";
			this.labelArea.Name = "labelArea";
			this.labelArea.UseMarkup = true;
			this.hbox5.Add (this.labelArea);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.labelArea]));
			w15.PackType = ((global::Gtk.PackType)(1));
			w15.Position = 3;
			w15.Fill = false;
			this.table2.Add (this.hbox5);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table2 [this.hbox5]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.LeftAttach = ((uint)(1));
			w16.RightAttach = ((uint)(2));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("День оплаты:");
			this.table2.Add (this.label10);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table2 [this.label10]));
			w17.TopAttach = ((uint)(5));
			w17.BottomAttach = ((uint)(6));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Номер договора<span foreground=\"red\">*</span>:");
			this.label5.UseMarkup = true;
			this.table2.Add (this.label5);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table2 [this.label5]));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Организация<span foreground=\"red\">*</span>:");
			this.label6.UseMarkup = true;
			this.table2.Add (this.label6);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
			w19.TopAttach = ((uint)(2));
			w19.BottomAttach = ((uint)(3));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Место<span foreground=\"red\">*</span>:");
			this.label7.UseMarkup = true;
			this.table2.Add (this.label7);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Арендатор<span foreground=\"red\">*</span>:");
			this.label8.UseMarkup = true;
			this.table2.Add (this.label8);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table2 [this.label8]));
			w21.TopAttach = ((uint)(3));
			w21.BottomAttach = ((uint)(4));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата подписания:");
			this.table2.Add (this.label9);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table2 [this.label9]));
			w22.TopAttach = ((uint)(4));
			w22.BottomAttach = ((uint)(5));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox8.Add (this.table2);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.table2]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
			this.table3.Name = "table3";
			this.table3.RowSpacing = ((uint)(6));
			this.table3.ColumnSpacing = ((uint)(6));
			// Container child table3.Gtk.Table+TableChild
			this.datepickerCancel = new global::QSWidgetLib.DatePicker ();
			this.datepickerCancel.Events = ((global::Gdk.EventMask)(256));
			this.datepickerCancel.Name = "datepickerCancel";
			this.datepickerCancel.Date = new global::System.DateTime (0);
			this.datepickerCancel.IsEditable = true;
			this.datepickerCancel.AutoSeparation = true;
			this.table3.Add (this.datepickerCancel);
			global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table3 [this.datepickerCancel]));
			w24.TopAttach = ((uint)(2));
			w24.BottomAttach = ((uint)(3));
			w24.LeftAttach = ((uint)(1));
			w24.RightAttach = ((uint)(2));
			w24.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.datepickerEnd = new global::QSWidgetLib.DatePicker ();
			this.datepickerEnd.Events = ((global::Gdk.EventMask)(256));
			this.datepickerEnd.Name = "datepickerEnd";
			this.datepickerEnd.Date = new global::System.DateTime (0);
			this.datepickerEnd.IsEditable = true;
			this.datepickerEnd.AutoSeparation = true;
			this.table3.Add (this.datepickerEnd);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table3 [this.datepickerEnd]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.LeftAttach = ((uint)(1));
			w25.RightAttach = ((uint)(2));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.datepickerStart = new global::QSWidgetLib.DatePicker ();
			this.datepickerStart.Events = ((global::Gdk.EventMask)(256));
			this.datepickerStart.Name = "datepickerStart";
			this.datepickerStart.Date = new global::System.DateTime (0);
			this.datepickerStart.IsEditable = true;
			this.datepickerStart.AutoSeparation = true;
			this.table3.Add (this.datepickerStart);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table3 [this.datepickerStart]));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата начала аренды<span foreground=\"red\">*</span>:");
			this.label11.UseMarkup = true;
			this.table3.Add (this.label11);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table3 [this.label11]));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата окончания аренды<span foreground=\"red\">*</span>:");
			this.label12.UseMarkup = true;
			this.table3.Add (this.label12);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table3 [this.label12]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table3.Gtk.Table+TableChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 1F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Дата расторжения:");
			this.table3.Add (this.label13);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table3 [this.label13]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox3.Add (this.table3);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.table3]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment8.Name = "GtkAlignment8";
			this.GtkAlignment8.LeftPadding = ((uint)(12));
			// Container child GtkAlignment8.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textComments = new global::Gtk.TextView ();
			this.textComments.CanFocus = true;
			this.textComments.Name = "textComments";
			this.textComments.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.textComments);
			this.GtkAlignment8.Add (this.GtkScrolledWindow);
			this.frame1.Add (this.GtkAlignment8);
			this.GtkLabel8 = new global::Gtk.Label ();
			this.GtkLabel8.Name = "GtkLabel8";
			this.GtkLabel8.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Комментарии</b>");
			this.GtkLabel8.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel8;
			this.vbox3.Add (this.frame1);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.frame1]));
			w34.Position = 1;
			this.hbox8.Add (this.vbox3);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox3]));
			w35.Position = 1;
			this.vbox2.Add (this.hbox8);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox8]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Услуги по договору</b>");
			this.label14.UseMarkup = true;
			this.vbox2.Add (this.label14);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label14]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeviewServices = new global::Gtk.TreeView ();
			this.treeviewServices.CanFocus = true;
			this.treeviewServices.Name = "treeviewServices";
			this.GtkScrolledWindow1.Add (this.treeviewServices);
			this.vbox2.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow1]));
			w39.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.buttonAddService = new global::Gtk.Button ();
			this.buttonAddService.CanFocus = true;
			this.buttonAddService.Name = "buttonAddService";
			this.buttonAddService.UseUnderline = true;
			this.buttonAddService.Label = global::Mono.Unix.Catalog.GetString ("Добавить");
			global::Gtk.Image w40 = new global::Gtk.Image ();
			w40.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			this.buttonAddService.Image = w40;
			this.hbox9.Add (this.buttonAddService);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.buttonAddService]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.buttonDelService = new global::Gtk.Button ();
			this.buttonDelService.CanFocus = true;
			this.buttonDelService.Name = "buttonDelService";
			this.buttonDelService.UseUnderline = true;
			this.buttonDelService.Label = global::Mono.Unix.Catalog.GetString ("Удалить");
			global::Gtk.Image w42 = new global::Gtk.Image ();
			w42.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			this.buttonDelService.Image = w42;
			this.hbox9.Add (this.buttonDelService);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.buttonDelService]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			this.vbox4.Add (this.hbox9);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox9]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			this.hbox7.Add (this.vbox4);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.vbox4]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.labelSum = new global::Gtk.Label ();
			this.labelSum.Name = "labelSum";
			this.labelSum.Xalign = 1F;
			this.labelSum.LabelProp = global::Mono.Unix.Catalog.GetString ("Сумма: 0 руб.");
			this.labelSum.Justify = ((global::Gtk.Justification)(1));
			this.hbox7.Add (this.labelSum);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.labelSum]));
			w46.Position = 1;
			this.vbox2.Add (this.hbox7);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox7]));
			w47.Position = 3;
			w47.Expand = false;
			w47.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w48.Position = 0;
			// Internal child bazar.Contract.ActionArea
			global::Gtk.HButtonBox w49 = this.ActionArea;
			w49.Name = "dialog1_ActionArea";
			w49.Spacing = 10;
			w49.BorderWidth = ((uint)(5));
			w49.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = global::Mono.Unix.Catalog.GetString ("О_тменить");
			global::Gtk.Image w50 = new global::Gtk.Image ();
			w50.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			this.buttonCancel.Image = w50;
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w51 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w49 [this.buttonCancel]));
			w51.Expand = false;
			w51.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = global::Mono.Unix.Catalog.GetString ("_OK");
			global::Gtk.Image w52 = new global::Gtk.Image ();
			w52.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
			this.buttonOk.Image = w52;
			w49.Add (this.buttonOk);
			global::Gtk.ButtonBox.ButtonBoxChild w53 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w49 [this.buttonOk]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 746;
			this.DefaultHeight = 521;
			this.Show ();
			this.comboPlaceT.Changed += new global::System.EventHandler (this.OnComboPlaceTChanged);
			this.comboPlaceNo.Changed += new global::System.EventHandler (this.OnComboPlaceNoChanged);
			this.buttonLesseeOpen.Clicked += new global::System.EventHandler (this.OnButtonLesseeOpenClicked);
			this.buttonLesseeEdit.Clicked += new global::System.EventHandler (this.OnButtonLesseeEditClicked);
			this.entryNumber.Changed += new global::System.EventHandler (this.OnEntryNumberChanged);
			this.entryNumber.Activated += new global::System.EventHandler (this.OnEntryActivated);
			this.comboOrg.Changed += new global::System.EventHandler (this.OnComboOrgChanged);
			this.datepickerStart.DateChanged += new global::System.EventHandler (this.OnDatepickerStartDateChanged);
			this.datepickerEnd.DateChanged += new global::System.EventHandler (this.OnDatepickerEndDateChanged);
			this.datepickerCancel.DateChanged += new global::System.EventHandler (this.OnDatepickerCancelDateChanged);
			this.treeviewServices.CursorChanged += new global::System.EventHandler (this.OnTreeviewServicesCursorChanged);
			this.buttonAddService.Clicked += new global::System.EventHandler (this.OnButtonAddServiceClicked);
			this.buttonDelService.Clicked += new global::System.EventHandler (this.OnButtonDelServiceClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
