
// This file has been generated by the GUI designer. Do not modify.
namespace bazar
{
	public partial class ExpenseSlip
	{
		private global::Gtk.VBox vbox2;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Table table1;
		private global::Gtk.ComboBox comboCash;
		private global::Gtk.ComboBox comboOperation;
		private global::Gtk.ComboBox comboOrg;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Entry entryContractor;
		private global::Gtk.Button buttonContractorEdit;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Entry entryAccountable;
		private global::Gtk.Button buttonAccountableEdit;
		private global::Gtk.Label label10;
		private global::Gtk.Label label3;
		private global::Gtk.Label label4;
		private global::Gtk.Label label5;
		private global::Gtk.Label labelAccountable;
		private global::Gtk.Table table2;
		private global::Gtk.ComboBox comboExpenseItem;
		private global::WidgetLib.DatePicker dateSlip;
		private global::Gtk.Entry entryNumber;
		private global::Gtk.Entry entryUser;
		private global::Gtk.Label label2;
		private global::Gtk.Label label6;
		private global::Gtk.Label label7;
		private global::Gtk.Label label9;
		private global::Gtk.Label labelExpenseItem;
		private global::Gtk.SpinButton spinSum;
		private global::Gtk.Label label1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView textviewDetails;
		private global::Gtk.Button buttonPrint;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget bazar.ExpenseSlip
			this.Name = "bazar.ExpenseSlip";
			this.Title = "Новый расходный ордер";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child bazar.ExpenseSlip.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(3));
			// Container child table1.Gtk.Table+TableChild
			this.comboCash = new global::Gtk.ComboBox ();
			this.comboCash.Name = "comboCash";
			this.table1.Add (this.comboCash);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboCash]));
			w2.TopAttach = ((uint)(2));
			w2.BottomAttach = ((uint)(3));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboOperation = global::Gtk.ComboBox.NewText ();
			this.comboOperation.AppendText ("Прочая выдача");
			this.comboOperation.AppendText ("Выдача подотчетному лицу");
			this.comboOperation.Name = "comboOperation";
			this.comboOperation.Active = 0;
			this.table1.Add (this.comboOperation);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboOperation]));
			w3.LeftAttach = ((uint)(1));
			w3.RightAttach = ((uint)(2));
			w3.XOptions = ((global::Gtk.AttachOptions)(4));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.comboOrg = new global::Gtk.ComboBox ();
			this.comboOrg.Name = "comboOrg";
			this.table1.Add (this.comboOrg);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.comboOrg]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.LeftAttach = ((uint)(1));
			w4.RightAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entryContractor = new global::Gtk.Entry ();
			this.entryContractor.CanFocus = true;
			this.entryContractor.Name = "entryContractor";
			this.entryContractor.IsEditable = false;
			this.entryContractor.InvisibleChar = '●';
			this.hbox3.Add (this.entryContractor);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.entryContractor]));
			w5.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonContractorEdit = new global::Gtk.Button ();
			this.buttonContractorEdit.TooltipMarkup = "Выбрать контрагента";
			this.buttonContractorEdit.CanFocus = true;
			this.buttonContractorEdit.Name = "buttonContractorEdit";
			this.buttonContractorEdit.UseUnderline = true;
			// Container child buttonContractorEdit.Gtk.Container+ContainerChild
			global::Gtk.Alignment w6 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w7 = new global::Gtk.HBox ();
			w7.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w7.Add (w8);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w10 = new global::Gtk.Label ();
			w7.Add (w10);
			w6.Add (w7);
			this.buttonContractorEdit.Add (w6);
			this.hbox3.Add (this.buttonContractorEdit);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.buttonContractorEdit]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			this.table1.Add (this.hbox3);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox3]));
			w15.TopAttach = ((uint)(3));
			w15.BottomAttach = ((uint)(4));
			w15.LeftAttach = ((uint)(1));
			w15.RightAttach = ((uint)(2));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryAccountable = new global::Gtk.Entry ();
			this.entryAccountable.CanFocus = true;
			this.entryAccountable.Name = "entryAccountable";
			this.entryAccountable.IsEditable = false;
			this.entryAccountable.InvisibleChar = '●';
			this.hbox4.Add (this.entryAccountable);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.entryAccountable]));
			w16.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonAccountableEdit = new global::Gtk.Button ();
			this.buttonAccountableEdit.CanFocus = true;
			this.buttonAccountableEdit.Name = "buttonAccountableEdit";
			this.buttonAccountableEdit.UseUnderline = true;
			// Container child buttonAccountableEdit.Gtk.Container+ContainerChild
			global::Gtk.Alignment w17 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w18 = new global::Gtk.HBox ();
			w18.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w19 = new global::Gtk.Image ();
			w19.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w18.Add (w19);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w21 = new global::Gtk.Label ();
			w18.Add (w21);
			w17.Add (w18);
			this.buttonAccountableEdit.Add (w17);
			this.hbox4.Add (this.buttonAccountableEdit);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.buttonAccountableEdit]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			this.table1.Add (this.hbox4);
			global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox4]));
			w26.TopAttach = ((uint)(4));
			w26.BottomAttach = ((uint)(5));
			w26.LeftAttach = ((uint)(1));
			w26.RightAttach = ((uint)(2));
			w26.XOptions = ((global::Gtk.AttachOptions)(4));
			w26.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = "<b>Вид операции:</b>";
			this.label10.UseMarkup = true;
			this.table1.Add (this.label10);
			global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table1 [this.label10]));
			w27.XOptions = ((global::Gtk.AttachOptions)(4));
			w27.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = "Организация<span foreground=\"red\">*</span>:";
			this.label3.UseMarkup = true;
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w28.TopAttach = ((uint)(1));
			w28.BottomAttach = ((uint)(2));
			w28.XOptions = ((global::Gtk.AttachOptions)(4));
			w28.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = "Касса<span foreground=\"red\">*</span>:";
			this.label4.UseMarkup = true;
			this.table1.Add (this.label4);
			global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
			w29.TopAttach = ((uint)(2));
			w29.BottomAttach = ((uint)(3));
			w29.XOptions = ((global::Gtk.AttachOptions)(4));
			w29.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = "Контрагент:";
			this.label5.UseMarkup = true;
			this.table1.Add (this.label5);
			global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
			w30.TopAttach = ((uint)(3));
			w30.BottomAttach = ((uint)(4));
			w30.XOptions = ((global::Gtk.AttachOptions)(4));
			w30.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.labelAccountable = new global::Gtk.Label ();
			this.labelAccountable.Name = "labelAccountable";
			this.labelAccountable.Xalign = 1F;
			this.labelAccountable.LabelProp = "Получатель:";
			this.labelAccountable.UseMarkup = true;
			this.table1.Add (this.labelAccountable);
			global::Gtk.Table.TableChild w31 = ((global::Gtk.Table.TableChild)(this.table1 [this.labelAccountable]));
			w31.TopAttach = ((uint)(4));
			w31.BottomAttach = ((uint)(5));
			w31.XOptions = ((global::Gtk.AttachOptions)(4));
			w31.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.table1]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.table2 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table2.Name = "table2";
			this.table2.RowSpacing = ((uint)(6));
			this.table2.ColumnSpacing = ((uint)(6));
			this.table2.BorderWidth = ((uint)(3));
			// Container child table2.Gtk.Table+TableChild
			this.comboExpenseItem = new global::Gtk.ComboBox ();
			this.comboExpenseItem.Name = "comboExpenseItem";
			this.table2.Add (this.comboExpenseItem);
			global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table2 [this.comboExpenseItem]));
			w33.TopAttach = ((uint)(3));
			w33.BottomAttach = ((uint)(4));
			w33.LeftAttach = ((uint)(1));
			w33.RightAttach = ((uint)(2));
			w33.XOptions = ((global::Gtk.AttachOptions)(4));
			w33.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.dateSlip = new global::WidgetLib.DatePicker ();
			this.dateSlip.Sensitive = false;
			this.dateSlip.Events = ((global::Gdk.EventMask)(256));
			this.dateSlip.Name = "dateSlip";
			this.dateSlip.Date = new global::System.DateTime (0);
			this.table2.Add (this.dateSlip);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table2 [this.dateSlip]));
			w34.TopAttach = ((uint)(1));
			w34.BottomAttach = ((uint)(2));
			w34.LeftAttach = ((uint)(1));
			w34.RightAttach = ((uint)(2));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryNumber = new global::Gtk.Entry ();
			this.entryNumber.Sensitive = false;
			this.entryNumber.CanFocus = true;
			this.entryNumber.Name = "entryNumber";
			this.entryNumber.Text = "Не назначен";
			this.entryNumber.IsEditable = false;
			this.entryNumber.InvisibleChar = '●';
			this.table2.Add (this.entryNumber);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryNumber]));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.entryUser = new global::Gtk.Entry ();
			this.entryUser.Sensitive = false;
			this.entryUser.CanFocus = true;
			this.entryUser.Name = "entryUser";
			this.entryUser.IsEditable = true;
			this.entryUser.InvisibleChar = '●';
			this.table2.Add (this.entryUser);
			global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table2 [this.entryUser]));
			w36.TopAttach = ((uint)(2));
			w36.BottomAttach = ((uint)(3));
			w36.LeftAttach = ((uint)(1));
			w36.RightAttach = ((uint)(2));
			w36.XOptions = ((global::Gtk.AttachOptions)(4));
			w36.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = "Номер ордера:";
			this.table2.Add (this.label2);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table2 [this.label2]));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = "Дата документа:";
			this.table2.Add (this.label6);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
			w38.TopAttach = ((uint)(1));
			w38.BottomAttach = ((uint)(2));
			w38.XOptions = ((global::Gtk.AttachOptions)(4));
			w38.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = "Пользователь:";
			this.table2.Add (this.label7);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table2 [this.label7]));
			w39.TopAttach = ((uint)(2));
			w39.BottomAttach = ((uint)(3));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = "Сумма<span foreground=\"red\">*</span>:";
			this.label9.UseMarkup = true;
			this.table2.Add (this.label9);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table2 [this.label9]));
			w40.TopAttach = ((uint)(4));
			w40.BottomAttach = ((uint)(5));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.labelExpenseItem = new global::Gtk.Label ();
			this.labelExpenseItem.Name = "labelExpenseItem";
			this.labelExpenseItem.Xalign = 1F;
			this.labelExpenseItem.LabelProp = "Статья расхода<span foreground=\"red\">*</span>:";
			this.labelExpenseItem.UseMarkup = true;
			this.table2.Add (this.labelExpenseItem);
			global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table2 [this.labelExpenseItem]));
			w41.TopAttach = ((uint)(3));
			w41.BottomAttach = ((uint)(4));
			w41.XOptions = ((global::Gtk.AttachOptions)(4));
			w41.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table2.Gtk.Table+TableChild
			this.spinSum = new global::Gtk.SpinButton (0, 100000000, 100);
			this.spinSum.CanFocus = true;
			this.spinSum.Name = "spinSum";
			this.spinSum.Adjustment.PageIncrement = 1000;
			this.spinSum.ClimbRate = 1;
			this.spinSum.Digits = ((uint)(2));
			this.spinSum.Numeric = true;
			this.table2.Add (this.spinSum);
			global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table2 [this.spinSum]));
			w42.TopAttach = ((uint)(4));
			w42.BottomAttach = ((uint)(5));
			w42.LeftAttach = ((uint)(1));
			w42.RightAttach = ((uint)(2));
			w42.XOptions = ((global::Gtk.AttachOptions)(4));
			w42.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox1.Add (this.table2);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.table2]));
			w43.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = "Основание:";
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow.BorderWidth = ((uint)(3));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewDetails = new global::Gtk.TextView ();
			this.textviewDetails.CanFocus = true;
			this.textviewDetails.Name = "textviewDetails";
			this.textviewDetails.AcceptsTab = false;
			this.textviewDetails.WrapMode = ((global::Gtk.WrapMode)(2));
			this.GtkScrolledWindow.Add (this.textviewDetails);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w47.Position = 2;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w48.Position = 0;
			// Internal child bazar.ExpenseSlip.ActionArea
			global::Gtk.HButtonBox w49 = this.ActionArea;
			w49.Name = "dialog1_ActionArea";
			w49.Spacing = 10;
			w49.BorderWidth = ((uint)(5));
			w49.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonPrint = new global::Gtk.Button ();
			this.buttonPrint.Sensitive = false;
			this.buttonPrint.CanFocus = true;
			this.buttonPrint.Name = "buttonPrint";
			this.buttonPrint.UseUnderline = true;
			// Container child buttonPrint.Gtk.Container+ContainerChild
			global::Gtk.Alignment w50 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w51 = new global::Gtk.HBox ();
			w51.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w52 = new global::Gtk.Image ();
			w52.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Button);
			w51.Add (w52);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w54 = new global::Gtk.Label ();
			w54.LabelProp = "Печать";
			w54.UseUnderline = true;
			w51.Add (w54);
			w50.Add (w51);
			this.buttonPrint.Add (w50);
			this.AddActionWidget (this.buttonPrint, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w58 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w49 [this.buttonPrint]));
			w58.Expand = false;
			w58.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseUnderline = true;
			// Container child buttonCancel.Gtk.Container+ContainerChild
			global::Gtk.Alignment w59 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w60 = new global::Gtk.HBox ();
			w60.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w61 = new global::Gtk.Image ();
			w61.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Menu);
			w60.Add (w61);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w63 = new global::Gtk.Label ();
			w63.LabelProp = "О_тменить";
			w63.UseUnderline = true;
			w60.Add (w63);
			w59.Add (w60);
			this.buttonCancel.Add (w59);
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w67 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w49 [this.buttonCancel]));
			w67.Position = 1;
			w67.Expand = false;
			w67.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.Sensitive = false;
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseUnderline = true;
			// Container child buttonOk.Gtk.Container+ContainerChild
			global::Gtk.Alignment w68 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w69 = new global::Gtk.HBox ();
			w69.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w70 = new global::Gtk.Image ();
			w70.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-ok", global::Gtk.IconSize.Menu);
			w69.Add (w70);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w72 = new global::Gtk.Label ();
			w72.LabelProp = "_OK";
			w72.UseUnderline = true;
			w69.Add (w72);
			w68.Add (w69);
			this.buttonOk.Add (w68);
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w76 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w49 [this.buttonOk]));
			w76.Position = 2;
			w76.Expand = false;
			w76.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 682;
			this.DefaultHeight = 319;
			this.Show ();
			this.buttonAccountableEdit.Clicked += new global::System.EventHandler (this.OnButtonAccountableEditClicked);
			this.buttonContractorEdit.Clicked += new global::System.EventHandler (this.OnButtonContractorEditClicked);
			this.comboOrg.Changed += new global::System.EventHandler (this.OnComboOrgChanged);
			this.comboOperation.Changed += new global::System.EventHandler (this.OnComboOperationChanged);
			this.comboCash.Changed += new global::System.EventHandler (this.OnComboCashChanged);
			this.spinSum.ValueChanged += new global::System.EventHandler (this.OnSpinSumValueChanged);
			this.spinSum.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnSpinSumChangeValue);
			this.comboExpenseItem.Changed += new global::System.EventHandler (this.OnComboIncomeItemChanged);
			this.buttonPrint.Clicked += new global::System.EventHandler (this.OnButtonPrintClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
